"""initialisation des tables

Revision ID: 0c3f06b41d52
Revises: 20e5db2e1fb8
Create Date: 2025-10-02 09:27:51.949446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3f06b41d52'
down_revision: Union[str, None] = '20e5db2e1fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
